'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Bestellung_Gericht
    Public Property Id As Integer
    Public Property IdBestellung As Integer
    Public Property IdWare As Integer

    Public Overridable Property Bestellungen As Bestellungen
    Public Overridable Property Gerichte As Gerichte

End Class
