'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Bestellungen
    Public Property Id As Integer
    Public Property Kundenname As String
    Public Property Kundenadresse As String
    Public Property Hausnummer As Short
    Public Property Preis As Decimal

    Public Overridable Property Bestellung_Gericht As ICollection(Of Bestellung_Gericht) = New HashSet(Of Bestellung_Gericht)

End Class
