'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Gerichte
    Public Property Id As Integer
    Public Property Name As String
    Public Property Beschreibung As String
    Public Property Photo As Byte()
    Public Property Zeigen As Boolean
    Public Property Zutaten As String
    Public Property Preis As Decimal

    Public Overridable Property Bestellung_Gericht As ICollection(Of Bestellung_Gericht) = New HashSet(Of Bestellung_Gericht)

End Class
