'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Gericht_Zutaten
    Public Property Id As Integer
    Public Property IdGericht As Integer
    Public Property IdZutat As Integer

    Public Overridable Property Zutaten As Zutaten

End Class
