'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Database1Entities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Database1Entities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Bestellungen() As DbSet(Of Bestellungen)
    Public Overridable Property Gericht_Zutaten() As DbSet(Of Gericht_Zutaten)
    Public Overridable Property Gerichte() As DbSet(Of Gerichte)
    Public Overridable Property Zutaten() As DbSet(Of Zutaten)
    Public Overridable Property Bestellung_Gericht() As DbSet(Of Bestellung_Gericht)

End Class
